language: r
sudo: required
cache: packages
dist: trusty
r:
  - oldrel
  - release
  - devel

r_github_packages:
    - robertzk/testthatsomemore
    - kirillseva/covr
r_binary_packages:
    - testthat
    - microbenchmark
    - crayon
    - roxygen2

after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  webhooks:
    urls:
       - https://webhooks.gitter.im/e/655fbe5e7a5067377f3f
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: G2TbZEtH1hTZR9dBaFVesZEP8RhzNvnQOrGBwqfJm2NxwBD13MPSiOyD/h3OiyxRfAA+lY9ttYCtUxecD5+23pwg057OU63iDT+0Y/r1b4f0fnzKJ9zWedBFpEnG8Ov1zyjr2IRR9TL/1FArA5oLaBb9Qgay9kDmLXZYXH10hoM=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
