language: c
dist: trusty
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r testthat microbenchmark crayon"
- "./travis-tool.sh install_github robertzk/testthatsomemore"
- "./travis-tool.sh github_package jimhester/covr"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: G2TbZEtH1hTZR9dBaFVesZEP8RhzNvnQOrGBwqfJm2NxwBD13MPSiOyD/h3OiyxRfAA+lY9ttYCtUxecD5+23pwg057OU63iDT+0Y/r1b4f0fnzKJ9zWedBFpEnG8Ov1zyjr2IRR9TL/1FArA5oLaBb9Qgay9kDmLXZYXH10hoM=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
